nodeLinker: node-modules

packageExtensions:
  "@nrwl/devkit@*":
    dependencies:
      nx: ^19.4.2
  cosmiconfig-typescript-loader@*:
    dependencies:
      "@types/node": ^20.14.10
      typescript: ^5.5.3

yarnPath: .yarn/releases/yarn-4.4.0.cjs
